name: coursera
services:
  react-app-conference-event-planner:
    build: .
    container_name: conference-event-planner
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0